version: "2"
run:
  allow-parallel-runners: true
  tests: false
linters:
  enable:
    - wsl
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
    - whitespace
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - legacy
    paths:
      - test/*
      - pkg/riverqueue/generate/generate.go
issues:
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/theopenlane/riverboat
  exclusions:
    generated: lax
    warn-unused: true
