version: "3"

includes:
  config:
    taskfile: ./configgen/Taskfile.yaml
  docker:
    taskfile: ./docker/Taskfile.yaml
    dir: ./docker
    aliases: [compose]

env:
  GOFLAGS: -buildvcs=false

tasks:
  default:
    silent: true
    cmds:
      - task --list

  ## Go tasks
  go:lint:
    desc: runs golangci-lint, the most annoying opinionated linter ever
    silent: true
    cmds:
      - |
        if [ "{{.INCLUDE_TRUST_CENTER}}" = "true" ]; then \
          golangci-lint run --build-tags=trustcenter --verbose --fix; \
        else \
          golangci-lint run --verbose --fix ; \
        fi

  go:lint:ci:
    desc: runs golangci-lint, the most annoying opinionated linter ever
    silent: true
    cmds:
      - |
        if [ "{{.INCLUDE_TRUST_CENTER}}" = "true" ]; then \
          golangci-lint run --build-tags=trustcenter --verbose; \
        else \
          golangci-lint run --verbose ; \
        fi

  go:fmt:
    desc: format all go code
    cmds:
      - go fmt ./...

  go:test:
    desc: runs and outputs results of created go tests
    silent: true
    aliases: [test]
    cmds:
      - |
        if [ "{{.INCLUDE_TRUST_CENTER}}" = "true" ]; then \
          go test -tags=trustcenter -v ./... ; \
        else \
          go test -v ./... ; \
        fi

  go:test:cover:
    desc: runs and outputs results of created go tests with coverage
    silent: true
    aliases: [cover]
    cmds:
      - |
        if [ "{{.INCLUDE_TRUST_CENTER}}" = "true" ]; then \
          go test -tags=trustcenter -v ./... -coverprofile=coverage.out ; \
        else \
          go test -v ./... -coverprofile=coverage.out ; \
        fi

  go:test:cover:out:
    desc: runs and outputs results of created go tests with coverage
    cmds:
      - task: go:test:cover
      - go tool cover -html=coverage.out

  go:tidy:
    desc: runs go mod tidy on the backend
    aliases: [tidy]
    cmds:
      - go mod tidy

  go:all:
    aliases: [go]
    desc: runs all go test and lint related tasks
    cmds:
      - task: go:tidy
      - task: go:fmt
      - task: go:lint
      - task: go:test

  go:build:
    desc: Runs go build for the riverboat server
    silent: true
    cmds:
      - |
        if [ "{{.INCLUDE_TRUST_CENTER}}" = "true" ]; then \
          go build -tags=trustcenter -o riverboat; \
        else \
          go build-o riverboat ; \
        fi

  go:build:ci:
    desc: Runs go build for the riverboat server
    silent: true
    cmds:
      - |
        if [ "{{.INCLUDE_TRUST_CENTER}}" = "true" ]; then \
          go build -tags=trustcenter -a -o bin/riverboat; \
        else \
          go build -a -o bin/riverboat ; \
        fi

  run:
    dotenv: ["{{.ENV}}/.env-dev"]
    silent: true
    desc: runs the riverboat server in dev mode, assumes all other dependencies (postgres) are running
    cmds:
      - |
        echo "Starting riverboat server..."
        if [ "{{.INCLUDE_TRUST_CENTER}}" = "true" ]; then \
          echo "Including Trust Center jobs"; \
          go run -tags=trustcenter main.go serve --debug --pretty; \
        else \
          go run main.go serve --debug --pretty ; \
        fi

  run-dev:
    dotenv: ["{{.ENV}}/.env-dev"]
    desc: runs the riverboat server in dev mode with dependencies in docker
    cmds:
      - task: docker:postgres
      - task: docker:ui:up
      - 'open "http://localhost:8082"'
      - task: run

  precommit-full:
    desc: Lint the project against all files
    cmds:
      - pre-commit install && pre-commit install-hooks
      - pre-commit autoupdate
      - pre-commit run --show-diff-on-failure --color=always --all-files

  generate:
    desc: generate mocks
    cmds:
      - go generate ./...

