// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPDFRenderer creates a new instance of MockPDFRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDFRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDFRenderer {
	mock := &MockPDFRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPDFRenderer is an autogenerated mock type for the PDFRenderer type
type MockPDFRenderer struct {
	mock.Mock
}

type MockPDFRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDFRenderer) EXPECT() *MockPDFRenderer_Expecter {
	return &MockPDFRenderer_Expecter{mock: &_m.Mock}
}

// HTMLToPDF provides a mock function for the type MockPDFRenderer
func (_mock *MockPDFRenderer) HTMLToPDF(ctx context.Context, html string) ([]byte, error) {
	ret := _mock.Called(ctx, html)

	if len(ret) == 0 {
		panic("no return value specified for HTMLToPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, html)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, html)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, html)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPDFRenderer_HTMLToPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTMLToPDF'
type MockPDFRenderer_HTMLToPDF_Call struct {
	*mock.Call
}

// HTMLToPDF is a helper method to define mock.On call
//   - ctx context.Context
//   - html string
func (_e *MockPDFRenderer_Expecter) HTMLToPDF(ctx any, html any) *MockPDFRenderer_HTMLToPDF_Call {
	return &MockPDFRenderer_HTMLToPDF_Call{Call: _e.mock.On("HTMLToPDF", ctx, html)}
}

func (_c *MockPDFRenderer_HTMLToPDF_Call) Run(run func(ctx context.Context, html string)) *MockPDFRenderer_HTMLToPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPDFRenderer_HTMLToPDF_Call) Return(bytes []byte, err error) *MockPDFRenderer_HTMLToPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockPDFRenderer_HTMLToPDF_Call) RunAndReturn(run func(ctx context.Context, html string) ([]byte, error)) *MockPDFRenderer_HTMLToPDF_Call {
	_c.Call.Return(run)
	return _c
}
