FROM ubuntu:26.04

# add non-root user
RUN useradd -u 1000 nonroot
USER nonroot

# Copy the binary
COPY riverboat /bin/riverboat

# Run the server on container startup
ENTRYPOINT [ "/bin/riverboat" ]
CMD ["serve"]
