refreshInterval: 600000000000
river:
    databasehost: postgres://postgres:password@0.0.0.0:5432/jobs?sslmode=disable
    defaultmaxretries: 10
    metrics:
        enablemetrics: false
        enablesemanticmetrics: true
        metricsdurationunit: ms
    queues: null
    workers:
        clearTrustCenterCacheWorker:
            config:
                enabled: false
                objectstorage:
                    devmode: false
                    enabled: true
                    keys:
                        - uploadFile
                    maxmemorymb: 0
                    maxsizemb: 0
                    providers:
                        cloudflarer2:
                            baseurl: http://localhost:17608/v1/files
                            bucket: ""
                            credentials:
                                accesskeyid: ""
                                accountid: ""
                                apitoken: ""
                                projectid: ""
                                secretaccesskey: ""
                            enabled: false
                            endpoint: ""
                            ensureavailable: false
                            proxypresignenabled: false
                            region: ""
                        database:
                            baseurl: http://localhost:17608/v1/files
                            bucket: ""
                            credentials:
                                accesskeyid: ""
                                accountid: ""
                                apitoken: ""
                                projectid: ""
                                secretaccesskey: ""
                            enabled: false
                            endpoint: ""
                            ensureavailable: false
                            proxypresignenabled: false
                            region: ""
                        disk:
                            baseurl: http://localhost:17608/v1/files
                            bucket: ""
                            credentials:
                                accesskeyid: ""
                                accountid: ""
                                apitoken: ""
                                projectid: ""
                                secretaccesskey: ""
                            enabled: false
                            endpoint: ""
                            ensureavailable: false
                            proxypresignenabled: false
                            region: ""
                        gcs:
                            baseurl: http://localhost:17608/v1/files
                            bucket: ""
                            credentials:
                                accesskeyid: ""
                                accountid: ""
                                apitoken: ""
                                projectid: ""
                                secretaccesskey: ""
                            enabled: false
                            endpoint: ""
                            ensureavailable: false
                            proxypresignenabled: false
                            region: ""
                        s3:
                            baseurl: http://localhost:17608/v1/files
                            bucket: ""
                            credentials:
                                accesskeyid: ""
                                accountid: ""
                                apitoken: ""
                                projectid: ""
                                secretaccesskey: ""
                            enabled: false
                            endpoint: ""
                            ensureavailable: false
                            proxypresignenabled: false
                            region: ""
        createcustomdomainworker:
            config:
                cloudflareapikey: ""
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
                validateinterval: 0
        createpirschdomainworker:
            config:
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
                pirschclientid: ""
                pirschclientsecret: ""
        databaseworker:
            config:
                baseUrl: http://localhost:1337
                debug: false
                enabled: true
                endpoint: query
        deletecustomdomainworker:
            config:
                cloudflareapikey: ""
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
                validateinterval: 0
        deleteexportcontentworker:
            config:
                cutoffduration: 0
                enabled: false
                interval: 0
                openlaneapihost: ""
                openlaneapitoken: ""
        deletepirschdomainworker:
            config:
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
                pirschclientid: ""
                pirschclientsecret: ""
        emailworker:
            config:
                devmode: true
                enabled: false
                fromemail: no-reply@example.com
                testdir: fixtures/email
                token: ""
        exportcontentworker:
            config:
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
        openlaneconfig:
            openlaneapihost: ""
            openlaneapitoken: ""
        slackworker:
            config:
                devmode: true
                enabled: false
                token: ""
        updatepirschdomainworker:
            config:
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
                pirschclientid: ""
                pirschclientsecret: ""
        validatecustomdomainworker:
            config:
                cloudflareapikey: ""
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
                validateinterval: 0
        watermarkdocworker:
            config:
                enabled: false
                openlaneapihost: ""
                openlaneapitoken: ""
